### ISSUE TITLE
Serverside errors on startup

### ISSUE THREAD

**Issue by ColdMeekly** [FerbFletchit/platform_procedure#2]
```lua
[ERROR] gamemodes/platform_procedure/entities/entities/pp_boss_turret/init.lua:7: attempt to call field 'AddNPCClassAlly' (a nil value)
1. unknown - gamemodes/platform_procedure/entities/entities/pp_boss_turret/init.lua:7
[ERROR] gamemodes/platform_procedure/entities/entities/pp_boss_worm/init.lua:28: table index is nil
1. unknown - gamemodes/platform_procedure/entities/entities/pp_boss_worm/init.lua:28
[ERROR] gamemodes/platform_procedure/entities/entities/pp_enemy_babyvoltigore/init.lua:7: attempt to call field 'AddNPCClassAlly' (a nil value)
1. unknown - gamemodes/platform_procedure/entities/entities/pp_enemy_babyvoltigore/init.lua:7
[ERROR] gamemodes/platform_procedure/entities/entities/pp_enemy_bullsquid/init.lua:24: table index is nil
1. unknown - gamemodes/platform_procedure/entities/entities/pp_enemy_bullsquid/init.lua:24
[ERROR] gamemodes/platform_procedure/entities/entities/pp_enemy_sentry/init.lua:33: table index is nil
1. unknown - gamemodes/platform_procedure/entities/entities/pp_enemy_sentry/init.lua:33
[ERROR] gamemodes/platform_procedure/entities/entities/pp_enemy_stukabat/init.lua:7: attempt to call field 'AddNPCClassAlly' (a nil value)
1. unknown - gamemodes/platform_procedure/entities/entities/pp_enemy_stukabat/init.lua:7
```

**Comment by FerbFletchit** [comment]
The gamemode does not work in single player, start the game as a peer to peer server.

**Comment by ColdMeekly** [comment]
I'm not on singleplayer, hosting on dedicated host. `start the game as a peer to peer server.` What do you mean by that

**Comment by ColdMeekly** [comment]
Perhaps it's the way I installed. I extracted the repo into the gamemodes folder and removed the `_master` from the name

**Comment by FerbFletchit** [comment]
The turret is no longer in the game, so for the time being, delete the folder pp_boss_turret from the entities folder, this will be resolved in the next update.

**Comment by FerbFletchit** [comment]
Make sure to add the NPC pack directly into your server addons. https://steamcommunity.com/workshop/filedetails/?id=1516699044

This appears to be due to the missing content. Ensure all of the required addons are on your server.

**Comment by FerbFletchit** [comment]
The required addons are on the right side: https://steamcommunity.com/sharedfiles/filedetails/?id=2183728122

**Comment by ColdMeekly** [comment]
My bad, didn't use the steam community page.

**Comment by FerbFletchit** [comment]
All good, I'll update the github description. Thank you!

**Comment by FerbFletchit** [comment]
I'll be updating the gamemode soon with many improvements, so look out for that.

**Comment by ColdMeekly** [comment]
Thanks for your quick response, hope you win! 🥇

**Comment by Aws0mee** [comment]
win or else

**Comment by FerbFletchit** [comment]
I did my best guys, the rest is up to the judges!

**Comment by Aws0mee** [comment]
if u don't win then this is rigged

**Comment by FerbFletchit** [comment]
The files have been updated, enjoy :)
